preset: psr12

enabled:
  - alpha_ordered_imports
  - array_indentation
  - cast_spaces
  - lowercase_cast
  - no_empty_phpdoc
  - no_extra_consecutive_blank_lines
  - no_unused_imports
  - phpdoc_indent
  - phpdoc_scalar
  - phpdoc_trim
  - single_line_after_imports
  - short_scalar_cast
  - yoda_style

disabled:
  - concat_with_spaces
