preset: psr12

enabled:
  - alpha_ordered_imports
  - array_indentation
  - cast_spaces
  - lowercase_cast
  - no_empty_phpdoc
  - no_extra_consecutive_blank_lines
  - no_unused_imports
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_scalar
  - short_scalar_cast
  - yoda_style

disabled:
  - concat_with_spaces
