language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.4
      env: STATIC_ANALYSIS=yes
      script: then php phpstan.phar analyse

before_script:
  - travis_retry composer update --no-interaction
  - if [ "$STATIC_ANALYSIS" != "" ]; then curl -L https://github.com/phpstan/phpstan/releases/download/0.12.32/phpstan.phar -o phpstan.phar; fi;

script:
  - vendor/bin/phpunit --verbose --coverage-text
